import os
from datetime import datetime


def generate_scaffold(domain, project_intent=None):
    """
    Generates base scaffold files.
    If project_intent is provided, writes UI_REQUIREMENTS.md.
    """
    _write_index_html()
    _write_style_css()
    _write_app_js()
    _write_ai_context()
    _write_ui_requirements(project_intent)


def _write_index_html():
    content = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Generated Static UI</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="style.css">
</head>
<body>

  <!-- UI markup goes here -->

  <script src="api.js"></script>
  <script src="app.js"></script>
</body>
</html>
"""
    _write_file("index.html", content)


def _write_style_css():
    content = """/* Base styles */

body {
  font-family: sans-serif;
  margin: 0;
  padding: 1rem;
}
"""
    _write_file("style.css", content)


def _write_app_js():
    content = """/* UI logic goes here */

// Example:
// document.getElementById("btn").addEventListener("click", async () => {
//   const result = await API.example(payload);
//   if (result.error) {
//     console.error(result.error);
//     return;
//   }
//   console.log(result.data);
// });
"""
    _write_file("app.js", content)


def _write_ai_context():
    content = """# AI CONTEXT — READ FIRST

You are working with a project generated by cuibuild.

This file defines strict rules you MUST follow.
Do not assume, infer, or invent anything outside this context.
"""
    _write_file("AI_CONTEXT.md", content)


def _write_ui_requirements(project_intent):
    if not project_intent:
        return

    timestamp = datetime.utcnow().isoformat()

    content = f"""# UI REQUIREMENTS

version: 1
captured_by: cuibuild
captured_at: {timestamp}

--- USER INTENT START ---

{project_intent}

--- USER INTENT END ---
"""
    _write_file("UI_REQUIREMENTS.md", content)


def _write_file(filename, content):
    if os.path.exists(filename):
        print(f"• Skipped {filename} (already exists)")
        return

    with open(filename, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"✔ Created {filename}")
